#!/bin/bash

function usage {
    local script=$(basename "$0")

    printf "USAGE: %s <dir> [<specific_target_image>]\n" "$script"
    printf "EXAMPLES:\n"
    printf "\t%s tacas26\n" "$script"
    printf "\t%s tacas26 fedora:latest\n" "$script"

    [[ -n $1 ]] && exit $1
}

[[ -z $1 ]] && usage 0

DIR="$1"
shift

DIRBASE=$(basename "$DIR")
DIRBASE=${DIRBASE%% *}

REPO=smts
TAG=latest

[[ -n $1 ]] && {
    TARGET=$1
    shift

    REPO+=-${TARGET%:*}
    tag=${TARGET#*:}
    [[ -n $tag ]] && TAG=$tag
}

REPO+=-$DIRBASE

IMAGE=$REPO:$TAG
